### ISSUE TITLE
no consigo que me mande los links a transmission

### ISSUE THREAD

**Issue by ezdakit** [jerosoler/NewPct-to-Transmission#1]
me funciona bien la búsqueda pero al pulsar el botón add no me carga los torrents en transmission.

Example app listening on port 3000!                                                                                                       
GET / 200 2898.464 ms - 656
GET /javascripts/getLista.js 200 33.481 ms - 467
GET /stylesheets/style.css 200 60.890 ms - 110
GET /javascripts/app.js 200 18.284 ms - 1189
GET /images/Loading_icon.gif 200 13.329 ms - 17490
GET LISTA                                                                                                                                 
GET /favicon.ico 404 282.513 ms - 1469
GET /getLista 200 2161.905 ms - 539018
GET /s/walking%20dead 200 471.138 ms - 686
GET /stylesheets/style.css 304 7.399 ms - -
GET /images/Loading_icon.gif 304 10.222 ms - -
GET /javascripts/getListaBusqueda.js 200 6.102 ms - 1100
GET /javascripts/app.js 304 1.342 ms - -
GET /getListaBusqueda?busqueda=walking%20dead 200 1623.145 ms - 11436
GET /getListaBusqueda2?busqueda=http%3A%2F%2Fwww.newpct.com%2Fseries-hd%2Fthe-walking-dead%2F1483 200 607.654 ms - 3671
LLAMADOhttp://www.newpct.com/descargar-seriehd/the-walking-dead/capitulo-85/hdtv-720p-ac3-5-1/                                            
LLAMADOhttp://www.newpct.com/descargar-seriehd/the-walking-dead/capitulo-85/hdtv-720p-ac3-5-1/                                            
LLAMADOhttp://www.newpct.com/descargar-seriehd/the-walking-dead/capitulo-85/hdtv-720p-ac3-5-1/                                            
LLAMADOhttp://www.newpct.com/descargar-seriehd/the-walking-dead/capitulo-84/hdtv-720p-ac3-5-1/                                            
LLAMADOhttp://www.newpct.com/descargar-seriehd/the-walking-dead/capitulo-84/hdtv-720p-ac3-5-1/                                            
POST /addtorrent - - ms - -                                                                                                               
LLAMADOhttp://www.newpct.com/descargar-seriehd/the-walking-dead/capitulo-85/hdtv-720p-ac3-5-1/                                            
POST /addtorrent - - ms - -                                                                                                               
LLAMADOhttp://www.newpct.com/descargar-seriehd/the-walking-dead/capitulo-85/hdtv-720p-ac3-5-1/                                            
POST /addtorrent - - ms - -                                                                                                               
POST /addtorrent - - ms - -                                                                                                               
POST /addtorrent - - ms - -                                                                                                               
POST /addtorrent - - ms - -                                                                                                               
POST /addtorrent - - ms - -

**Comment by jerosoler** [comment]
Tienes protegido transmission con usuario y password?

**Comment by ezdakit** [comment]
No

**Comment by jerosoler** [comment]
Prueba a cambiar en el archivo /routes/index.js
` var textofiltrar = $("#tab1").text();`
esto por:
` var textofiltrar = $("#tab1").html();`

**Comment by jerosoler** [comment]
@ezdakit puedes probar este otro que es para que se descargue automaticamente. 
https://github.com/jerosoler/newpct-auto

En principio estan funcionando los dos.

**Comment by jerosoler** [comment]
@ezdakit Actualizado repositorio puedes probar ahora.
