### ISSUE TITLE
Algunas búsquedas da errores en nombre y otras no las muestra al completo

### ISSUE THREAD

**Issue by jab3** [jerosoler/NewPct-to-Transmission#2]
Muy buenas! muy fan de tus dos apps de newpct que las tengo desde los principios!

Desde que se actualizo la web con el nuevo código he podido observar estos dos pares de fallos

1.- Lista la búsqueda con nombres incompletos: si le das a buscar = anillos. Para buscar el señor de los anillos solo te lista: El Se.

2.- Cuando buscas una serie, como por ejemplo, La cúpula, solo te lista tercera y segunda temporada. Desde la web están todos los capítulos, entiendo que falta el botón de pasar pagina, y cuando le das al nuevo botón VIEW solo te muestra algunos capítulos.

Espero haberme explicado bien jeje.

Saludos y gracias

**Comment by jerosoler** [comment]
Hola! 

Gracias!

1. Esta no la conocía. (Este debe ser tema de caracteres)
2. Esta me di cuenta ayer. 

Este finde me lo miro y te digo! 

Jero

**Comment by jerosoler** [comment]
@jab3 
Problema número 1: 
Parece que es cosa suya ya que al realizar la búsqueda en Newpct:
http://www.newpct.com/?page=buscar&q=anillos

Sale igual.

Problema número 2: Ya estoy trabajando en ello. 

Jero

**Comment by jab3** [comment]
Muchas gracias! 

Del tema 1 no me había percatado.

Por otra parte, habría posibilidad de añadirle un botón para las búsquedas pero por calidad?

Cuando tenía el código antiguo la web, modificada el tuyo añadiéndole un botón para que me buscará bluray 1080, ahora con el nuevo código tuyo, al añadirlo hace caso omiso . No se si es complicado o no la posibilidad. 

Gracias

**Comment by jerosoler** [comment]
No problem! Añadire un buscador por calidad!

**Comment by jerosoler** [comment]
Añadido buscador de calidad

Y también paginación en busqueda y en subbusqueda. 

Commit: https://github.com/jerosoler/NewPct-to-Transmission/commit/3fb59420b1f77cf9e165db921cc052001d756583

Puedes actualizarlo con el commando:
`git pull`

Reinicias y listo.

**Comment by jerosoler** [comment]
@jab3 
Actualizado! ;)

**Comment by jab3** [comment]
buah! funciona de 10! es la caña ya para mi, perfecto!

lo que si he visto, que creo que es una tontería a nivel personal ya que no influye para nada, yo antes el tema de la calidad lo usaba para listar todo el contenido de esa calidad, me explico, que cuando quería ver todo el contenido en BluRay 1080p, simplemente elegía la calidad y le daba a buscar, o ponía un espacio en blanco y listo.... pues lo he probado sin poner nada, no busca nada y si pongo el espacio en blanco , me busca como he dicho todo el contenido de 1080 y esto ha pasado:


Emoji color='blue'> [BluRay color='blue'> 1080p][AC3 color='blue'> 5.1 color='blue'> Castellano color='blue'> DTS color='blue'> 5.1-Ingles+Subs][ES-EN]
--
Add | CHiPs color='blue'> [BluRay color='blue'> 1080p][AC3 color='blue'> 5.1 color='blue'> Castellano color='blue'> DTS color='blue'> 5.1-Ingles+Subs][ES-EN]

y si pongo lo mismo en una serie:

Heroes color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> - color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> Temporada color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> 3 color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> Completa color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> color=blue> Capitulos 0 al 25 Espa�ol Castellano Calidad [ HDTV 720p AC3 5.1 ]

 
EDITO: he buscado de esta manera en la web, y pasa justo lo mismo, así que es fallo de la misma web!


Pedazo de curro!
muchas gracias!

**Comment by jerosoler** [comment]
@jab3 

He encontrado una solución a tu problema! Ahora si escribes un espacio en blanco te permitira hacer la busqueda que comentas.  

Commit: https://github.com/jerosoler/NewPct-to-Transmission/commit/64bd524e6ead4459379e7ff3a81b4daa44f758ab

Jero

**Comment by jab3** [comment]
Pues ahora me hace lo contrario, si escribo un espacio en blanco y le pongo la calidad, no encuentra nada, antes aunque saliera el código mal, te listaba todo por ejemplo en 1080.

Ya te digo esto es mas que nada una tontería de uso personal que si funciona mal por culpa de la web...  si quieres no busques solución.

Ya te digo que que lo demás funciona de fabula

**Comment by jerosoler** [comment]
@jab3 

Corregido ahora deberia de funcionar bien si solo escribes un espacio.
https://github.com/jerosoler/NewPct-to-Transmission/commit/51cad6e3a0b39a93e611520874cf233d0268f9cf

Jero

**Comment by jab3** [comment]
ahora si!!! esta perfecto! muchisimas gracias!
