### ISSUE TITLE
No envía a Transmission

### ISSUE THREAD

**Issue by izalai** [jerosoler/NewPct-to-Transmission#3]
Hola, un par de meses atrás me funcionaba correctamente. 
He bajado la nueva versión, he probado a quitar contraseña del transmission, pero sigue sin agregarme ningún enlace al pulsar el botón de "Add"
Gracias

**Comment by jerosoler** [comment]
@izalai 

Prueba a ejecutar un enlace normal:
`transmission-remote -a URL_TORRENT`
Haber si lo añade a transmission.

Si no prueba esto para saber si te esta cogiendo bien la url:
Añadir la linea de **console.log(urltorrent)** en la posición que indico. Para ver que url te encuentra. 
` var textofiltrar = $("#tab1 script").html();
  var urltorrent = textofiltrar.match(/http:\/\/.*?\.html/);
 console.log(urltorrent); 
` 

Jero

**Comment by izalai** [comment]
Esto me reporta cuando pincho sobre cualquier enlace

LLAMADOhttp://www.newpct.com/descargar-pelicula/bastard/blurayrip/
[ 'http://tumejorserie.com/descargar/index.php?link=descargar-torrent/099004_bastard-blurayrip.html',
  index: 227,
  input: '\n\t\t\t\t\t\t\t\t  function openTorrent()\n\t\t\t\t\t\t\t\t  {\n\t\t\t\t\t\t\t\t\t  \n\t\t\t\t\t\t\t\t\tvar link = "http://adplexmedia.adk2x.com/imp?p=75989146&ct=html&ap=1304";\n\t\t\t\t\t\t\t\t  \twindow.open(link);\n\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t  \twindow.location.href = "http://tumejorserie.com/descargar/index.php?link=descargar-torrent/099004_bastard-blurayrip.html";\t\n\n\t\t\t\t\t\t\t\t  }\t\n\t\t\t\t\t\t\t\t  ' ]

**Comment by izalai** [comment]
Era un problema de autenticación, añadiendo al transmission --auth username:password -l ya me añade los enlaces.

Muchas gracias

**Comment by jerosoler** [comment]
Perfect! ;)
